### ISSUE TITLE
Geoquake: Widgets de WebAppBuilder

### ISSUE THREAD

**Issue by anmaro13** [Geo-Developers/talks#10]
# Titulo:
Geoquake: Widgets de WebAppBuilder

# Objetivo: 
Aprender a crear widgets mediante WebAppBuilder utilizando la API de JS de Esri, dentro del entorno del proyecto Geoquake.

# Nivel: Intermedio

# Descripción:
Geoquake  es un proyecto centrado en la aportación de soluciones GIS a las diferentes situaciones que pudieran ocurrir en caso de catástrofe por terremoto. Es un proyecto que consta con una serie de aplicaciones creadas mediante el constructor de WebAppBuilder. Durante la charla, se verá más en profundidad cómo se han creado una serie de widgets incluidos en las aplicaciones, los cuales utilizan bootstrap, y en concreto el widget de cálculo de seguros, donde el usuario puede configurar los parámetros desde una interfaz gráfica y flexible.

# Duración
30 min - 1hora

**Comment by ntkog** [comment]
Done! https://www.meetup.com/Geo-Developers/events/240236187/
