### ISSUE TITLE
Developer Summit 2017 - Madrid

### ISSUE THREAD

**Issue by aicelm** [Geo-Developers/talks#13]
# Título
Developer Summit 2017
# Descripción

Os contaremos las novedades presentadas en el Developer Summit de [Palm Springs](http://www.esri.com/events/devsummit), donde hablaremos de:

 - ArcGIS for API JS 4.3
 - Runtime SDK v100
 - SmartMapping
 - Web AppBuilder
 - Python API
 - Nuevos vector tiles, rendimiento 3D y muchas cosas más...

Para saber más puedes visitar la [página del evento](http://esri-es.github.io/devsummits-esri-spain/2017/)

# Ponentes
- Alejandro Pequeño | [GeoDeveloper](http://www.geodevelopers.org/members/208473967) | [LinkedIn](https://www.linkedin.com/in/alejandro-peque%C3%B1o-pulleiro-a6157b123/)
- Andrea Martín | [GeoDeveloper](http://www.geodevelopers.org/members/221360040) | [LinkedIn](https://www.linkedin.com/in/anmaro13/)
- Antonio Remirez | [Geodeveloper](http://www.geodevelopers.org/members/192403731) | [LinkedIn](https://www.linkedin.com/in/aremirez/)
- Leticia Matas | [GeoDeveloper](http://www.geodevelopers.org/members/218283724) | [LinkedIn](https://www.linkedin.com/in/matasalvarezleticia/)
- Raúl Jiménez | [Geodeveloper](http://www.geodevelopers.org/members/139909072) | [LinkedIn](https://www.linkedin.com/in/jimenezortegaraul/)

# Nivel
Intermedio

# Duración
Todo el día. 
Desde las 8:30 a las 17:30

**Comment by ntkog** [comment]
Done! https://www.meetup.com/Geo-Developers/events/240633446/
