### ISSUE TITLE
Taller API REST ArcGIS

### ISSUE THREAD

**Issue by aicelm** [Geo-Developers/talks#16]
# Título
Taller API REST ArcGIS

# Descripción

Repetiremos el taller que se hizo en el Developer Summit el pasado 28 de junio. 

Haremos un repaso de la API REST de ArcGIS y aprenderemos a crear un servicio, añadir capas, manipular sus datos, pero también para buscar y gestionar items dentro de una organización. 

Aprenderemos a gestionar toda esta información con Postman y veremos las ventajas que tiene el utilizarlo. 

# Bio del Ponente

Andrea Martín | [GeoDeveloper](https://www.meetup.com/es-ES/Geo-Developers/members/221360040/) | [LinkedIn](https://www.linkedin.com/in/anmaro13/)
Leticia Matas | [GeoDeveloper](https://www.meetup.com/es-ES/Geo-Developers/members/218283724/) | [LinkedIn](https://www.linkedin.com/in/matasalvarezleticia/)

# Nivel

Iniciación

# Duración

Aproximadamente 1h 30m

# Fecha propuesta

Martes 11 de julio a las 18h

**Comment by ntkog** [comment]
Done! https://www.meetup.com/es-ES/preview/Geo-Developers/events/241361197
